/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'
import { Route as LocationIndexRouteImport } from './routes/location/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsNewIndexRouteImport } from './routes/admin/events/new/index'
import { Route as AdminEventsIdEditIndexRouteImport } from './routes/admin/events/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/admin/events/',
  path: '/admin/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewIndexRoute = AdminEventsNewIndexRouteImport.update({
  id: '/admin/events/new/',
  path: '/admin/events/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIdEditIndexRoute = AdminEventsIdEditIndexRouteImport.update({
  id: '/admin/events/$id/edit/',
  path: '/admin/events/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/events': typeof EventsIndexRoute
  '/location': typeof LocationIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/new': typeof AdminEventsNewIndexRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/about': typeof AboutIndexRoute
  '/admin': typeof AdminIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/events': typeof EventsIndexRoute
  '/location': typeof LocationIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/events/new': typeof AdminEventsNewIndexRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/about/': typeof AboutIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/events/': typeof EventsIndexRoute
  '/location/': typeof LocationIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/events/new/': typeof AdminEventsNewIndexRoute
  '/admin/events/$id/edit/': typeof AdminEventsIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/$id'
    | '/about'
    | '/admin'
    | '/calendar'
    | '/characters'
    | '/contact'
    | '/events'
    | '/location'
    | '/ranking'
    | '/admin/events'
    | '/admin/events/new'
    | '/admin/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters/$id'
    | '/about'
    | '/admin'
    | '/calendar'
    | '/characters'
    | '/contact'
    | '/events'
    | '/location'
    | '/ranking'
    | '/admin/events'
    | '/admin/events/new'
    | '/admin/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/characters/$id'
    | '/about/'
    | '/admin/'
    | '/calendar/'
    | '/characters/'
    | '/contact/'
    | '/events/'
    | '/location/'
    | '/ranking/'
    | '/admin/events/'
    | '/admin/events/new/'
    | '/admin/events/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharactersIdRoute: typeof CharactersIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LocationIndexRoute: typeof LocationIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsNewIndexRoute: typeof AdminEventsNewIndexRoute
  AdminEventsIdEditIndexRoute: typeof AdminEventsIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new/': {
      id: '/admin/events/new/'
      path: '/admin/events/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$id/edit/': {
      id: '/admin/events/$id/edit/'
      path: '/admin/events/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminEventsIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharactersIdRoute: CharactersIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LocationIndexRoute: LocationIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsNewIndexRoute: AdminEventsNewIndexRoute,
  AdminEventsIdEditIndexRoute: AdminEventsIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
