/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _notFoundRouteImport } from './routes/__not-found'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingIndexRouteImport } from './routes/ranking/index'
import { Route as LocationIndexRouteImport } from './routes/location/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'

const _notFoundRoute = _notFoundRouteImport.update({
  id: '/__not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationIndexRoute = LocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/about': typeof AboutIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/location': typeof LocationIndexRoute
  '/ranking': typeof RankingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/characters/$id': typeof CharactersIdRoute
  '/about': typeof AboutIndexRoute
  '/calendar': typeof CalendarIndexRoute
  '/characters': typeof CharactersIndexRoute
  '/contact': typeof ContactIndexRoute
  '/location': typeof LocationIndexRoute
  '/ranking': typeof RankingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__not-found': typeof _notFoundRoute
  '/characters/$id': typeof CharactersIdRoute
  '/about/': typeof AboutIndexRoute
  '/calendar/': typeof CalendarIndexRoute
  '/characters/': typeof CharactersIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/location/': typeof LocationIndexRoute
  '/ranking/': typeof RankingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/$id'
    | '/about'
    | '/calendar'
    | '/characters'
    | '/contact'
    | '/location'
    | '/ranking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters/$id'
    | '/about'
    | '/calendar'
    | '/characters'
    | '/contact'
    | '/location'
    | '/ranking'
  id:
    | '__root__'
    | '/'
    | '/__not-found'
    | '/characters/$id'
    | '/about/'
    | '/calendar/'
    | '/characters/'
    | '/contact/'
    | '/location/'
    | '/ranking/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _notFoundRoute: typeof _notFoundRoute
  CharactersIdRoute: typeof CharactersIdRoute
  AboutIndexRoute: typeof AboutIndexRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  LocationIndexRoute: typeof LocationIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__not-found': {
      id: '/__not-found'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof _notFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/': {
      id: '/location/'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _notFoundRoute: _notFoundRoute,
  CharactersIdRoute: CharactersIdRoute,
  AboutIndexRoute: AboutIndexRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  LocationIndexRoute: LocationIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
